Feat create account
GoLembrar/GoLembrar-server pull request #1
Opened 2023-12-09 23:25 UTC by lucasnathandev

Foi realizada a operação de criar usuário. 
Pontos importantes:  
Foi utilizado o bcrypt para criar o hash da senha; DTO CreateUserDto foi atualizado com decorators do class-validator para validar email e senha; Foi utilizado o prisma para gravar os dados no banco Postgres.

2023-12-10 14:14 UTC, Rip4568 commented
Fazendo review....

2023-12-10 15:15 UTC, Rip4568 commented
ao meu ver tudo certo.

2023-12-10 16:42 UTC, erickmarx requested changes

2023-12-10 16:42 UTC, erickmarx commented on src/user/user.service.ts
> +  private async generateHashedPassword(password: string) {
isto deveria ser um util.
uma classe chamada Hash e ter dois metodos chamados: hash e compare

2023-12-10 16:42 UTC, erickmarx commented on src/user/user.service.ts
> +    const salt = await bcrypt.genSalt();
utilize node:crypto ao invés de bcrypt
https://nodejs.org/api/crypto.html

2023-12-10 17:00 UTC, lucasnathandev commented on src/user/user.service.ts
> +        password: false,
Esqueci de retirar eu tava logando esse usuário criado. Mas tava funcionando sim.

2023-12-10 17:02 UTC, lucasnathandev commented on src/user/user.service.ts
> +    const salt = await bcrypt.genSalt();
Blz, mas mesmo assim teria que usar o bcrypt para comparar depois não teria?

2023-12-10 20:55 UTC, erickmarx commented on src/user/user.service.ts
> +    const salt = await bcrypt.genSalt();
estude este codigo:
`import { randomBytes, scryptSync } from 'node:crypto';

export class HashUtil {
  static hash(word: string): string {
    const salt = randomBytes(8).toString('hex');

    const derivedKey = scryptSync(word, salt, 64);

    return salt + ':' + derivedKey.toString('hex');
  }

  static verify(word: string, hash: string): boolean {
    if (!word || !hash) return false;

    const [salt, key] = hash.split(':');

    const derivedKey = scryptSync(word, salt, 64);

    return key === derivedKey.toString('hex');
  }
}
`

2023-12-11 18:58 UTC, lucasnathandev commented
Corrigi os pontos citados na review

2023-12-11 20:31 UTC, erickmarx requested changes

2023-12-11 20:31 UTC, erickmarx commented on src/user/entities/user.entity.ts
> +export class User {}
O que é isto?

2023-12-11 20:31 UTC, erickmarx commented on src/common/utils/hashUtil.ts
> +    const salt =
use o valor fixo 12 para o salt

2023-12-11 20:41 UTC, erickmarx approved these changes

2023-12-11 20:41 UTC, merged